name: ngrouter
repository: https://github.com/angulardart-community/angular
description: |
  Router for AngularDart. It enables navigation from one view to the next as users perform tasks.
version: 3.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ngdart: ^7.0.0
  collection: ^1.15.0
  js: ^0.6.3
  meta: ^1.3.0

dev_dependencies:
  analyzer: ^4.2.0
  lints: ^2.0.0
  async: ^2.5.0
  ngtest: ^4.1.0
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_web_compilers: ^3.0.0
  mockito: ^5.0.0
  test: ^1.16.0
