name: ngtest
repository: https://github.com/angulardart-community/angular
description: |
  Testing runner and library for AngularDart. This package is necessary to write component tests for AngularDart components.
version: 4.1.0

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  ngdart: ^7.0.0
  collection: ^1.15.0
  meta: ^1.3.0

dev_dependencies:
  analyzer: ^4.2.0
  lints: ^2.0.0
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_web_compilers: ^3.0.0
  test: ^1.16.0
